CREATE table MUSIC (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    RELEASE_TIME DATE,
    GENRE_ID int,
    MUSICIAN_ID int,
    SINGER_ID int,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (MUSICIAN_ID) REFERENCES MUSICIAN(ID),
    FOREIGN KEY (SINGER_ID) REFERENCES SINGER(ID)
);

CREATE TABLE MUSICIAN (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    SEX varchar(10) CHARSET utf8,
    BIRTHDAY DATETIME
);

CREATE TABLE SINGER (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    SEX varchar(10) CHARSET utf8,
    BIRTHDAY DATETIME
);

CREATE TABLE GENRE (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8
);


CREATE TABLE USER (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(30) CHARSET utf8,
    USERNAME varchar(30) CHARSET utf8,
    PASSWORD varchar(30) CHARSET utf8
);

CREATE TABLE PLAYLIST (
  USER_ID int NOT NULL,
  MUSIC_ID int NOT NULL,
  PRIMARY KEY (USER_ID, MUSIC_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  FOREIGN KEY (MUSIC_ID) REFERENCES MUSIC(ID)
) ;

-- 
INSERT INTO PLAYLIST (NAME) VALUES ("Personal");

INSERT INTO GENRE (NAME) VALUES ("Cổ trang");
INSERT INTO GENRE (NAME) VALUES ("Rap");
INSERT INTO GENRE (NAME) VALUES ("Trữ tình");
INSERT INTO GENRE (NAME) VALUES ("Cách mạng");
INSERT INTO GENRE (NAME) VALUES ("Thiếu nhi");
INSERT INTO GENRE (NAME) VALUES ("Trẻ");
INSERT INTO GENRE (NAME) VALUES ("Hip hop");

INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Đen Vâu", "Male", "1995-5-5");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Thái Trinh", "Female", "1994-7-23");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Tú", "Male", "1995-1-6");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("BinZ", "Male", "1998-5-14");

INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Miu Lê", "Female", "1995-5-5");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Chipu", "Female", "1994-7-23");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Trung Quân", "Không rõ", "1995-1-6");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("OSad", "Male", "1998-5-14");


INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICIAN_ID, SINGER_ID) VALUES ("Một triệu năm", "2020-1-1", 1, 2, 1);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICIAN_ID, SINGER_ID) VALUES ("Renai Circulation", "2019-6-6", 1, 2, 4);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICIAN_ID, SINGER_ID) VALUES ("Quên hết âu lo", "2020-4-1", 2, 1, 1);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICIAN_ID, SINGER_ID) VALUES ("Trời xanh", "2020-4-1", 3, 1, 1);	

INSERT INTO USER (NAME, USERNAME, PASSWORD) VALUES ("Thảo", "thao", 123);	
INSERT INTO USER (NAME, USERNAME, PASSWORD) VALUES ("Tiên", "tien", 123);	



INSERT INTO PLAYLIST(USER_ID, MUSIC_ID) VALUES (1,6);
INSERT INTO PLAYLIST(USER_ID, MUSIC_ID) VALUES (1,3);
INSERT INTO PLAYLIST(USER_ID, MUSIC_ID) VALUES (1,4);

ALTER TABLE MUSIC CHANGE `MUSICAN_ID` `MUSICIAN_ID` int;
SELECT GENRE_ID, count(*) as QUANTITY FROM MUSIC GROUP BY GENRE_ID;
SELECT * FROM MUSICIAN;
SELECT * FROM MUSIC;
SELECT * FROM GENRE;
SELECT * FROM SINGER;
SELECT* FROM USER;
SELECT * FROM PLAYLIST;
SELECT MUSIC FROM MUSIC, PLAYLIST WHERE MUSIC.ID=PLAYLIST.MUSIC_ID AND PLAYLIST.USER_ID=1;
DELETE FROM MUSICIAN WHERE ID > 0;
DELETE FROM SINGER WHERE ID > 0;
DELETE FROM GENRE WHERE ID > 0;
DELETE FROM MUSIC WHERE ID>0;

DROP TABLE MUSIC;

DROP TABLE SINGER;
DROP TABLE GENRE;
DROP TABLE MUSICAN;
DROP TABLE PLAYLIST

