CREATE table MUSIC (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    RELEASE_TIME DATE,
    GENRE_ID int,
    MUSICAN_ID int,
    SINGER_ID int,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (MUSICAN_ID) REFERENCES MUSICAN(ID),
    FOREIGN KEY (SINGER_ID) REFERENCES SINGER(ID)
);

CREATE TABLE MUSICAN (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    SEX varchar(10) CHARSET utf8,
    BIRTHDAY DATETIME
);

CREATE TABLE SINGER (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8,
    SEX varchar(10) CHARSET utf8,
    BIRTHDAY DATETIME
);

CREATE TABLE GENRE (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME varchar(30) CHARSET utf8
);

-- 
INSERT INTO GENRE (NAME) VALUES ("Cổ trang");
INSERT INTO GENRE (NAME) VALUES ("Rap");
INSERT INTO GENRE (NAME) VALUES ("Trữ tình");
INSERT INTO GENRE (NAME) VALUES ("Cách mạng");
INSERT INTO GENRE (NAME) VALUES ("Thiếu nhi");
INSERT INTO GENRE (NAME) VALUES ("Trẻ");
INSERT INTO GENRE (NAME) VALUES ("Hip hop");

INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Đen Vâu", "Nam", "1995-5-5");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Thái Trinh", "Nư", "1994-7-23");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("Tú", "Nam", "1995-1-6");
INSERT INTO MUSICIAN (NAME, SEX, BIRTHDAY) VALUES ("BinZ", "Nam", "1998-5-14");

INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Miu Lê", "Nữ", "1995-5-5");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Chipu", "Nữ", "1994-7-23");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("Trung Quân", "Không rõ", "1995-1-6");
INSERT INTO SINGER (NAME, SEX, BIRTHDAY) VALUES ("OSad", "Nam", "1998-5-14");


INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICAN_ID, SINGER_ID) VALUES ("Một triệu năm", "2020-1-1", 1, 2, 1);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICAN_ID, SINGER_ID) VALUES ("Renai Circulation", "2019-6-6", 5, 2, 4);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICAN_ID, SINGER_ID) VALUES ("Quên hết âu lo", "2020-4-1", 6, 1, 1);	
INSERT INTO MUSIC (NAME, RELEASE_TIME, GENRE_ID, MUSICAN_ID, SINGER_ID) VALUES ("Trời xanh", "2020-4-1", 1, 1, 1);	


ALTER TABLE MUSIC CHANGE `MUSICAN_ID` `MUSICIAN_ID` int;
SELECT GENRE_ID, count(*) as QUANTITY FROM MUSIC GROUP BY GENRE_ID;
SELECT * FROM MUSICIAN;
SELECT * FROM MUSIC;
SELECT * FROM GENRE;
DELETE FROM MUSIC WHERE ID > 4;